<?php

return [
    'free-fire' => [
        'name' => 'Free Fire',
        'unit' => 'Diamonds',
        'title' => 'Free Fire Diamonds',
        'image' => 'assets/games/free-fire.jpg',
        'subtitle' => 'Bangladesh · ID Code',
        'region' => 'Bangladesh',
        'player_label' => 'Player ID',
        'placeholder' => 'Enter your player ID',
        'help' => 'Open Free Fire profile and copy the numeric ID shown below your username.',
        'input_mode' => 'numeric',
        'packages' => [
            ['name' => '25 Diamonds', 'price' => 25],
            ['name' => '50 Diamonds', 'price' => 40],
            ['name' => '115 Diamonds', 'price' => 85],
            ['name' => '240 Diamonds', 'price' => 165],
            ['name' => '355 Diamonds', 'price' => 240],
            ['name' => '480 Diamonds', 'price' => 320],
            ['name' => '610 Diamonds', 'price' => 405],
            ['name' => '850 Diamonds', 'price' => 565],
            ['name' => '1090 Diamonds', 'price' => 725],
            ['name' => 'Weekly Pass', 'price' => 160],
            ['name' => 'Monthly Pass', 'price' => 795],
            ['name' => '7 Days Evo Access', 'price' => 125],
        ],
    ],
    'pubg-mobile' => [
        'name' => 'PUBG Mobile',
        'unit' => 'UC',
        'title' => 'PUBG Mobile UC',
        'image' => 'assets/games/pubg-mobile.jpg',
        'subtitle' => 'Global · Player ID',
        'region' => 'Global Server',
        'player_label' => 'Player ID',
        'placeholder' => 'Enter your PUBG Mobile player ID',
        'help' => 'Open your PUBG Mobile profile and copy the numeric Player ID.',
        'input_mode' => 'numeric',
        'packages' => [
            ['name' => '60 UC', 'price' => 95],
            ['name' => '325 UC', 'price' => 480],
            ['name' => '660 UC', 'price' => 950],
            ['name' => '1800 UC', 'price' => 2350],
            ['name' => '3850 UC', 'price' => 4650],
            ['name' => '8100 UC', 'price' => 9250],
            ['name' => 'Royale Pass', 'price' => 1200],
        ],
    ],
    'mobile-legends' => [
        'name' => 'Mobile Legends',
        'unit' => 'Diamonds',
        'title' => 'Mobile Legends Diamonds',
        'image' => 'assets/games/mobile-legends.jpg',
        'subtitle' => 'Global · User ID',
        'region' => 'Global Server',
        'player_label' => 'User ID & Zone ID',
        'placeholder' => 'Example: 12345678 (1234)',
        'help' => 'Enter your Mobile Legends User ID and Zone ID from your profile.',
        'input_mode' => 'text',
        'packages' => [
            ['name' => '86 Diamonds', 'price' => 160],
            ['name' => '172 Diamonds', 'price' => 310],
            ['name' => '257 Diamonds', 'price' => 450],
            ['name' => '429 Diamonds', 'price' => 720],
            ['name' => '706 Diamonds', 'price' => 1150],
            ['name' => 'Weekly Diamond Pass', 'price' => 180],
            ['name' => 'Twilight Pass', 'price' => 850],
        ],
    ],
    'call-of-duty' => [
        'name' => 'Call of Duty Mobile',
        'unit' => 'CP',
        'title' => 'Call of Duty CP',
        'image' => 'assets/games/call-of-duty-mobile.jpg',
        'subtitle' => 'Garena · Player ID',
        'region' => 'Garena Server',
        'player_label' => 'Player ID',
        'placeholder' => 'Enter your Call of Duty Mobile player ID',
        'help' => 'Open your Call of Duty Mobile profile and copy the Player ID.',
        'input_mode' => 'text',
        'packages' => [
            ['name' => '80 CP', 'price' => 100],
            ['name' => '420 CP', 'price' => 480],
            ['name' => '880 CP', 'price' => 950],
            ['name' => '2400 CP', 'price' => 2450],
            ['name' => '5000 CP', 'price' => 4900],
            ['name' => '10800 CP', 'price' => 9900],
        ],
    ],
    'valorant' => [
        'name' => 'Valorant',
        'unit' => 'Points',
        'title' => 'Valorant Points',
        'image' => 'assets/games/valorant.webp',
        'subtitle' => 'AP · Riot ID',
        'region' => 'AP Server',
        'player_label' => 'Riot ID',
        'placeholder' => 'Enter your Riot ID (Name#Tag)',
        'help' => 'Enter your Riot ID and tagline exactly as shown in your Riot profile.',
        'input_mode' => 'text',
        'packages' => [
            ['name' => '475 VP', 'price' => 450],
            ['name' => '1000 VP', 'price' => 900],
            ['name' => '2050 VP', 'price' => 1750],
            ['name' => '3650 VP', 'price' => 3000],
            ['name' => '5350 VP', 'price' => 4300],
            ['name' => '11000 VP', 'price' => 8500],
        ],
    ],
];
